"""This module processes intents and determines a text response.

Attributes:
    STATIC_RESPONSES (dict): a dictionary of lists for static response types.

Example Intent Model:
    {
        query_text: "I\'ll take white side."
        parameters {
            fields {
                key: "BoardSide"
                value {
                    string_value: "white"
                }
            }
        }
        all_required_params_present: true
        fulfillment_text: "Great, you\'ll play white side then!"
        fulfillment_messages {
            text {
                text: "Great, you\'ll play white side then!"
            }
        }
        intent {
            name: "projects/chess-master-andy-mhyo/agent/intents/6fafe557-d27b-41e7-bef0-204a87036e2c"
            display_name: "Choose Side Intent"
        }
        intent_detection_confidence: 1.0
        language_code: "en"
    }

"""
from .utils import INTENT_MAPPING, RESPONSE_TYPES, get_random_choice
from . import choose_side


STATIC_RESPONSES = {
    RESPONSE_TYPES.HELLO: [
        "Hi! How are you?",
        "Hey, what's up?",
        "Yo, how's it going?"
    ],
    RESPONSE_TYPES.FALLBACK: [
        "I didn't get that. Can you say it again?",
        "I missed what you said. What was that?",
        "Sorry, could you say that again?",
        "Can you say that again?",
        "One more time?",
        "What was that?",
        "Say that one more time?",
        "I'm not sure I understood that."
    ]
}


def determine_response_from_intent(data):
    """Determines the response for an intent.

    Args:
        data (dict): the intent query response generated by Dialogflow.

    Returns:
        str: the response that should be given, as text.

    """

    # Determine the response type from the intent
    response_type = INTENT_MAPPING.get(data.intent.name)
    response_choice = "No response."

    # Handle more complex responses
    if response_type == RESPONSE_TYPES.CHOOSE_SIDE:
        response_choice = choose_side.handle(data)
    else:
        # Catch for all static responses
        response_choice = get_random_choice(
            STATIC_RESPONSES.get(response_type))

    # Return the determined response
    return response_choice
