"""This module contains functions that are related to the Dialogflow API.

Attributes:
    PROJECT_ID: the ID of the gcloud project.
    LANGUAGE_CODE: the language code of words being interpreted.

"""
from google.cloud import dialogflow

PROJECT_ID = "chess-master-andy-mhyo"
LANGUAGE_CODE = "en-US"


def perform_intent_query(session_id, text):
    """Detects the intent from a user's words.

    Args:
        session_id (str): the unique session ID to use for Dialogflow.
        text (str): the words that the user spoke.

    Returns:
        dict: the response generated by Dialogflow.

    """
    session_client = dialogflow.SessionsClient()

    session = session_client.session_path(PROJECT_ID, session_id)
    print(f"Session path: {session}\n")

    text_input = dialogflow.TextInput(
        text=text, language_code=LANGUAGE_CODE)

    query_input = dialogflow.QueryInput(text=text_input)

    response = session_client.detect_intent(
        request={"session": session, "query_input": query_input}
    )

    print("=" * 20)
    print(f"Query text: {response.query_result.query_text}")
    print(
        "Detected intent: {} (confidence: {})\n".format(
            response.query_result.intent.display_name,
            response.query_result.intent_detection_confidence,
        )
    )
    print("Fulfillment text: {}\n".format(
        response.query_result.fulfillment_text))

    print(response.query_result)

    return response.query_result
