"""This module processes intents and determines a text response.

Attributes:
    INTENT_NAME_BASE (str): The base of the name for an intent
    RESPONSE_TYPES (Enum): An enum for response types.
    INTENT_MAPPING (dict): Contains a mapping of intent IDs to responses.
    RESPONSE_LIST (dict): Contains all static responses and the base for all
        dynamic responses.

Example Intent:
    {
        query_text: "hello"
        action: "input.welcome"
        parameters {
        }
        all_required_params_present: true
        fulfillment_text: "Hi! How are you doing?"
        fulfillment_messages {
            text {
            text: "Hi! How are you doing?"
            }
        }
        intent {
            name: "projects/chess-master-andy-mhyo/agent/intents/fc298129-5845-44dc-a976-b7d6ca2f14c3"
            display_name: "Default Welcome Intent"
        }
        intent_detection_confidence: 1.0
        language_code: "en"
    }

"""
import random
from enum import Enum

INTENT_NAME_BASE = "projects/chess-master-andy-mhyo/agent/intents/"

RESPONSE_TYPES = Enum(
    "RESPONSE_TYPES",
    "HELLO FALLBACK"
)


INTENT_MAPPING = {
    INTENT_NAME_BASE + "2ab3d889-b6eb-494e-b822-9992da79280c": RESPONSE_TYPES.FALLBACK,
    INTENT_NAME_BASE + "fc298129-5845-44dc-a976-b7d6ca2f14c3": RESPONSE_TYPES.HELLO
}


RESPONSE_LIST = {
    RESPONSE_TYPES.HELLO: [
        "Hi! How are you?",
        "Hey, what's up?",
        "Yo, how's it going?"
    ],
    RESPONSE_TYPES.FALLBACK: [
        "I didn't get that. Can you say it again?",
        "I missed what you said. What was that?",
        "Sorry, could you say that again?",
        "Can you say that again?",
        "One more time?",
        "What was that?",
        "Say that one more time?"
    ]
}


def determine_response_from_intent(data):
    """Determines the response for an intent.

    Args:
        data (dict): the intent query response generated by Dialogflow.

    Returns:
        str: the response that should be given, as text.

    """
    response_type = INTENT_MAPPING.get(data.intent.name)
    response_list = RESPONSE_LIST.get(response_type)

    # TODO: add custom logic for intents with parameters

    return random.choice(response_list)
